"""empty message

Revision ID: 1b092a35c3e0
Revises: cc98b98c26e9
Create Date: 2021-09-25 16:41:09.650024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b092a35c3e0'
down_revision = 'cc98b98c26e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric', sa.Column('desc', sa.Text(), nullable=True))
    op.drop_column('metric', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric', sa.Column('description', sa.TEXT(), nullable=True))
    op.drop_column('metric', 'desc')
    # ### end Alembic commands ###
