"""Added coach_importance to technique

Revision ID: 2dcc4f4d78e2
Revises: 543d4a576dbd
Create Date: 2021-09-19 22:17:15.760203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dcc4f4d78e2'
down_revision = '543d4a576dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technique', sa.Column('coach_importance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technique', 'coach_importance')
    # ### end Alembic commands ###
