"""made lastname 32 characters

Revision ID: 33108cccddb9
Revises: b49c88850da9
Create Date: 2021-10-25 19:16:55.430088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33108cccddb9'
down_revision = 'b49c88850da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'lastname',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
