"""added coach_id to Entry

Revision ID: 456791aaef05
Revises: 9e2b7459af5d
Create Date: 2021-11-25 22:30:39.886044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456791aaef05'
down_revision = '9e2b7459af5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coach_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_column('coach_id')

    # ### end Alembic commands ###
