"""added Entry and Entry note tables to store all entires

Revision ID: 50b995ebbd22
Revises: a66661bb44b4
Create Date: 2021-11-25 19:32:14.983359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b995ebbd22'
down_revision = 'a66661bb44b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empmetrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('team', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('for_cox', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_rating', sa.Integer(), nullable=True),
    sa.Column('coach_importance', sa.Integer(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('view_allowed', sa.Boolean(), nullable=True),
    sa.Column('has_update', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('empmetric_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empmetric_id'], ['empmetrics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('emp_metrics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emp_metrics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tag', sa.VARCHAR(length=5), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('desc', sa.TEXT(), nullable=True),
    sa.Column('team', sa.VARCHAR(length=20), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('for_cox', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('entry_note')
    op.drop_table('entry')
    op.drop_table('empmetrics')
    # ### end Alembic commands ###
