"""added date-created to user

Revision ID: 57644412dfc7
Revises: fa14c35048fc
Create Date: 2021-10-17 11:43:57.684781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57644412dfc7'
down_revision = 'fa14c35048fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_created')
    # ### end Alembic commands ###
