"""empty message

Revision ID: 5c35d40c3692
Revises: 29d0f068987e
Create Date: 2021-10-02 19:29:37.149879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c35d40c3692'
down_revision = '29d0f068987e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uuid', sa.String(length=60), nullable=True))
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.drop_column('user', 'uuid')
    # ### end Alembic commands ###
