"""added deleted column to user

Revision ID: 96bd08d540f1
Revises: 80b88a99a8fd
Create Date: 2021-10-09 19:00:44.532811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96bd08d540f1'
down_revision = '80b88a99a8fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted')
    # ### end Alembic commands ###
