"""added is coxswain to user

Revision ID: a09db88cb0e0
Revises: c03f4c8fa611
Create Date: 2021-10-02 19:00:19.454263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09db88cb0e0'
down_revision = 'c03f4c8fa611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_coxswain', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_coxswain')
    # ### end Alembic commands ###
