"""added has set boolean to technique

Revision ID: a158db4aa4fd
Revises: 2dcc4f4d78e2
Create Date: 2021-09-20 22:11:20.614876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a158db4aa4fd'
down_revision = '2dcc4f4d78e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technique', sa.Column('has_set', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technique', 'has_set')
    # ### end Alembic commands ###
