"""added deleted to user and has_updated to metric

Revision ID: ae365edbe338
Revises: afe9f933303b
Create Date: 2021-10-09 23:28:44.328481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae365edbe338'
down_revision = 'afe9f933303b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric', sa.Column('has_update', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted')
    op.drop_column('metric', 'has_update')
    # ### end Alembic commands ###
