"""removed deleted column, added is_head to user

Revision ID: afe9f933303b
Revises: 96bd08d540f1
Create Date: 2021-10-09 19:31:44.046415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe9f933303b'
down_revision = '96bd08d540f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_head', sa.Boolean(), nullable=True))
    op.drop_column('user', 'deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deleted', sa.BOOLEAN(), nullable=True))
    op.drop_column('user', 'is_head')
    # ### end Alembic commands ###
