"""added mood to status

Revision ID: b49c88850da9
Revises: 51a072ebe49a
Create Date: 2021-10-25 18:45:03.303599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49c88850da9'
down_revision = '51a072ebe49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('mood', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'mood')
    # ### end Alembic commands ###
