"""added desc to metric

Revision ID: cc98b98c26e9
Revises: 9bb435ed562f
Create Date: 2021-09-25 16:39:03.000974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc98b98c26e9'
down_revision = '9bb435ed562f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric', sa.Column('tag', sa.String(length=50), nullable=True))
    op.add_column('metric', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('metric', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('metric', 'metric_tag')
    op.drop_column('metric', 'metric_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric', sa.Column('metric_name', sa.VARCHAR(length=50), nullable=True))
    op.add_column('metric', sa.Column('metric_tag', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('metric', 'description')
    op.drop_column('metric', 'name')
    op.drop_column('metric', 'tag')
    # ### end Alembic commands ###
