"""removed has_update from Entry since it's redundant

Revision ID: d0265c268456
Revises: 50b995ebbd22
Create Date: 2021-11-25 19:55:36.206064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0265c268456'
down_revision = '50b995ebbd22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_column('has_update')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_update', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
