"""Added technique table

Revision ID: dee55d7bb23f
Revises: ad586b1eee29
Create Date: 2021-09-05 22:42:26.508117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee55d7bb23f'
down_revision = 'ad586b1eee29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_rating', sa.Integer(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_importance', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technique')
    # ### end Alembic commands ###
