"""Added view_allowed column to technique

Revision ID: ef5be88b8c83
Revises: dee55d7bb23f
Create Date: 2021-09-06 13:16:29.360706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5be88b8c83'
down_revision = 'dee55d7bb23f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technique', sa.Column('view_allowed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technique', 'view_allowed')
    # ### end Alembic commands ###
