"""changed coach key to is_coach

Revision ID: f948f5e693d9
Revises: a09db88cb0e0
Create Date: 2021-10-02 19:06:02.007518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f948f5e693d9'
down_revision = 'a09db88cb0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_coach', sa.Boolean(), nullable=True))
    op.drop_column('user', 'coach_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('coach_key', sa.VARCHAR(length=6), nullable=False))
    op.drop_column('user', 'is_coach')
    # ### end Alembic commands ###
